# Manual Steps
 # webserver
# sudo apt update
# sudo apt install nginx -y
# sudo apt install unzip -y 

  # running the website
# cd /tmp
# wget https://www.free-css.com/assets/files/free-css-templates/download/page295/sbs.zip
# unzip sbs.zip
# sudo mv sbs-html/ /var/www/html/skate


---
- name: deploy a website
  hosts: all
  become: true
  tasks:
    - name: install nginx and unzip
      ansible.builtin.apt:
        name:
          - nginx
          - unzip
        update_cache: yes
        state: present
    - name: Download a website
      ansible.builtin.get_url:
        url: https://www.free-css.com/assets/files/free-css-templates/download/page295/sbs.zip
        dest: /tmp/sbs.zip
    - name: unzip the website
      ansible.builtin.unarchive:
        src: /tmp/sbs.zip
        dest: /tmp
        remote_src: yes
    - name: Copy HTML files to web server directory
      ansible.builtin.copy:
        src: /tmp/sbs-html/
        dest: /var/www/html/skating
        remote_src: true
      
  